version: '3.5'

services:
  web:
    image: dev.cryptec.at:5000/root/bokstaever:feature-deployment
    volumes:
      - "media:/media"
    environment:
      DATABASE_URL: postgres://bokstaever:3f893ef5c467799@db/bokstaever
      ALLOWED_HOSTS: "['example.com']"
      DEBUG: "False"
      SECRET_KEY: 0a4d3159be7ce53744b7e79968324503e482257c

  caddy:
    image: dev.cryptec.at:5000/root/bokstaever/caddy:feature-deployment
    volumes:
      - "media:/media"
    ports:
      - "80:80"
  db:
    image: postgres:latest
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: bokstaever
      POSTGRES_PASSWORD: 3f893ef5c467799
      POSTGRES_DB: dragonfruit

volumes:
  db: {}
  media: {}
