# Generated by Django 3.0.8 on 2020-07-07 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
