# Generated by Django 3.0.8 on 2020-07-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_image_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="feed",
            field=models.BooleanField(default=False, verbose_name="In feed"),
        ),
        migrations.AlterField(
            model_name="image",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="image",
            name="files",
            field=models.ManyToManyField(to="images.ImageFile", verbose_name="Files"),
        ),
        migrations.AlterField(
            model_name="image",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="container",
                to="images.ImageFile",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="height",
            field=models.IntegerField(verbose_name="Height"),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="image_file",
            field=models.FileField(upload_to="", verbose_name="Image file"),
        ),
        migrations.AlterField(
            model_name="imagefile",
            name="width",
            field=models.IntegerField(verbose_name="Width"),
        ),
    ]
