# Generated by Django 2.0.4 on 2018-08-16 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bokstaever", "0019_settings_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("images", models.ManyToManyField(to="bokstaever.Image")),
            ],
        ),
        migrations.AddField(
            model_name="page",
            name="gallery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bokstaever.Gallery",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="gallery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bokstaever.Gallery",
            ),
        ),
    ]
