# Generated by Django 3.0.4 on 2020-03-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bokstaever", "0032_pagemodel_show_menu"),
    ]

    operations = [
        migrations.DeleteModel(name="Settings",),
    ]
