# Generated by Django 3.0.8 on 2020-07-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bokstaever", "0033_delete_settings"),
    ]

    operations = [
        migrations.RemoveField(model_name="databasepage", name="draft",),
    ]
