# Generated by Django 3.0.8 on 2020-07-13 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("images", "0004_auto_20200713_1943"),
        ("bokstaever", "0035_auto_20200711_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databasepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.Image",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="databasepage",
            name="text",
            field=models.TextField(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="databasepage",
            name="type",
            field=models.CharField(
                choices=[
                    ("md", "Markdown"),
                    ("mdhtml", "Markdown with inline HTML"),
                    ("html", "HTML"),
                    ("raw", "Raw, linebreaks are rendered"),
                ],
                default="md",
                max_length=6,
                verbose_name="Typ",
            ),
        ),
        migrations.AlterField(
            model_name="filepage",
            name="path",
            field=models.CharField(max_length=200, verbose_name="Path"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="images",
            field=models.ManyToManyField(to="images.Image", verbose_name="Images"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="pagemodel",
            name="headline",
            field=models.CharField(max_length=200, verbose_name="Headline"),
        ),
        migrations.AlterField(
            model_name="pagemodel",
            name="show_menu",
            field=models.BooleanField(default=True, verbose_name="Show menu"),
        ),
        migrations.AlterField(
            model_name="pagemodel",
            name="slug",
            field=models.SlugField(max_length=200, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="draft",
            field=models.BooleanField(default=False, verbose_name="Draft"),
        ),
        migrations.AlterField(
            model_name="post",
            name="editors",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Editors"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="headline",
            field=models.CharField(max_length=200, verbose_name="Headline"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.Image",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateField(auto_now_add=True, verbose_name="Published"),
        ),
        migrations.AlterField(
            model_name="post", name="text", field=models.TextField(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[
                    ("md", "Markdown"),
                    ("mdhtml", "Markdown with inline HTML"),
                    ("html", "HTML"),
                    ("raw", "Raw, linebreaks are rendered"),
                ],
                default="md",
                max_length=6,
                verbose_name="Typ",
            ),
        ),
    ]
