# Generated by Django 2.0.4 on 2018-07-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bokstaever", "0003_auto_20180501_1757"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post", options={"ordering": ["-published", "-pk"]},
        ),
        migrations.RenameField(
            model_name="post", old_name="url_slug", new_name="slug",
        ),
        migrations.AlterField(
            model_name="file",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="bokstaever.Image",
            ),
        ),
    ]
