# Generated by Django 2.0.4 on 2018-07-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bokstaever", "0006_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
