# Generated by Django 2.0.4 on 2018-07-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bokstaever", "0011_auto_20180726_0900"),
    ]

    operations = [
        migrations.RemoveField(model_name="file", name="image",),
        migrations.DeleteModel(name="File",),
    ]
