# Generated by Django 2.0.4 on 2018-08-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bokstaever", "0013_auto_20180731_0827"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page", old_name="name", new_name="headline",
        ),
    ]
