# Generated by Django 2.0.4 on 2018-08-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bokstaever", "0015_settings_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="page", name="draft", field=models.BooleanField(default=False),
        ),
    ]
