# Generated by Django 2.0.4 on 2018-08-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0016_page_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('md', 'Markdown'), ('mdhtml', 'Markdown with inline HTML'), ('html', 'HTML')], default='md', max_length=6),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('md', 'Markdown'), ('mdhtml', 'Markdown with inline HTML'), ('html', 'HTML')], default='md', max_length=6),
        ),
    ]
