# Generated by Django 2.0.4 on 2018-09-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bokstaever", "0021_auto_20180817_0900"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="pagesize",
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
