# Generated by Django 2.1.1 on 2018-09-29 09:37

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def forward(apps, schema_editor):
    Settings = apps.get_model('bokstaever', 'Settings')

    try:
        settings = Settings.objects.get(pk=1)

        # Rename themes to name instead css files
        if settings.theme == 'css/brevlada.css':
            settings.theme = 'brevlada'
        if settings.theme == 'css/frimarke.css':
            settings.theme = 'frimarke'

        settings.save()
    except ObjectDoesNotExist:
        pass


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0022_settings_pagesize'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
