# Generated by Django 2.2 on 2019-04-09 13:08

from django.db import migrations

def forwards(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Page = apps.get_model('bokstaever', 'Page')
    DatabasePage = apps.get_model('bokstaever', 'DatabasePage')

    for page in Page.objects.all():
        DatabasePage.objects.create(
            pk=page.pk,
            headline=page.headline,
            slug=page.slug,
            image=page.image,
            text=page.text,
            type=page.type,
            draft=page.draft
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0025_auto_20190409_1307'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
