# Generated by Django 2.2 on 2019-04-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0026_auto_20190406_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='theme',
        ),
        migrations.AddField(
            model_name='settings',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bokstaever.Bundle'),
        ),
    ]
