# Generated by Django 2.2 on 2019-04-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0027_auto_20190409_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image',
        ),
    ]
