# Generated by Django 2.2 on 2019-04-06 19:05

from django.db import migrations

def forwards(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    Settings = apps.get_model('bokstaever', 'Settings')
    Bundle = apps.get_model('bokstaever', 'Bundle')

    bundle, _ = Bundle.objects.get_or_create(slug='default')
    settings, _ = Settings.objects.get_or_create(pk=1)

    settings.bundle = bundle
    settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0027_auto_20190406_1905'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
