# Generated by Django 2.2 on 2019-04-18 08:55

from django.db import migrations

def forwards(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return

    OldImage = apps.get_model('bokstaever', 'Image')
    Image = apps.get_model('images', 'Image')
    ImageFile = apps.get_model('images', 'ImageFile')

    for image in OldImage.objects.all():
        f = ImageFile.objects.create(
            image_file=image.image,
            height=image.image.height,
            width=image.image.width
        )

        img = Image.objects.create(
            pk=image.pk,
            title=image.title,
        )

        img.files.add(f)

class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0028_auto_20190417_1629'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
