# Generated by Django 2.2 on 2019-04-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0028_auto_20190406_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokstaever.Bundle'),
        ),
    ]
