# Generated by Django 2.2 on 2019-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0029_auto_20190406_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BundlePage',
            new_name='CustomPage',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='bundle',
        ),
        migrations.AddField(
            model_name='settings',
            name='pages',
            field=models.ManyToManyField(to='bokstaever.CustomPage'),
        ),
        migrations.DeleteModel(
            name='Bundle',
        ),
    ]
