# Generated by Django 2.2 on 2019-04-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0030_auto_20190418_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
