# Generated by Django 2.2 on 2019-04-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0031_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
    ]
