# Generated by Django 2.0.4 on 2018-07-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0005_auto_20180724_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My nice page', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
