# Generated by Django 2.0.4 on 2018-07-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0007_settings_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
