# Generated by Django 2.0.4 on 2018-07-26 08:50

from django.db import migrations


def forward(apps, schema_editor):
    images = apps.get_model('bokstaever', 'Image')
    for image in images.objects.all():
        image.image = image.files.first().path
        image.thumbnail = image.files.last().path
        image.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bokstaever', '0009_auto_20180726_0849'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
